routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

//
// 登入和登出
Route::middleware(['web'])->group(function () {
    Route::middleware(['guest.dashboard'])->group(function () {
        Route::get('login', 'AuthController@login')->name('dashboard.auth.login');
        Route::post('login', 'AuthController@loginHandler')->name('dashboard.auth.login-handler');
    });

    Route::post('logout', 'AuthController@logoutHandler')->name('dashboard.auth.logout-handler');
});

//
// 管理平台
Route::middleware(['web', 'auth.dashboard'])->group(function () {
    Route::get('/', 'HomeController@index')->name('dashboard.index');

    // 焦点图
    Route::any('carousels/{carousel}/delete', 'CarouselController@destroy')->name('dashboard.carousels.delete')->where('carousel', '[0-9]+');
    Route::name('dashboard')->resource('carousels', 'CarouselController');

    // 用户
    Route::prefix('users')->group(function () {
        Route::get('/', 'UserController@index')->name('dashboard.users.index');
        Route::get('{user}', 'UserController@show')->name('dashboard.users.show')->where('user', '[0-9]+');
    });

    // 评论
    Route::prefix('comments')->group(function () {
        Route::get('/', 'CommentController@index')->name('dashboard.comments.index');
        Route::get('{comment}', 'CommentController@show')->name('dashboard.comments.show')->where('comment', '[0-9]+');
    });

    // 点赞
    Route::prefix('')->group(function () {
        Route::get('thumbs', 'ThumbController@index')->name('dashboard.thumbs.index');
    });

    // 用户报告
    Route::prefix('user-reports')->group(function () {
        Route::get('/', 'UserReportController@index')->name('dashboard.user-reports.index');
    });

    // 数据分析
    Route::prefix('analytics')->group(function () {
        Route::get('/', function () {
            return redirect()->route('dashboard.analytics.users');
        })->name('dashboard.analytics.index');

        Route::get('increases', 'Analytics\IncreaseController@index')->name('dashboard.analytics.increases');

        Route::get('users', 'Analytics\UserController@index')->name('dashboard.analytics.users');
    });

    // 访客日志
    Route::prefix('visitor-logs')->group(function () {
        Route::get('/', 'VisitorLogController@index')->name('dashboard.visitor-logs.index');
        Route::get('date', 'VisitorLogController@date')->name('dashboard.visitor-logs.date');
    });

    // 其他
    Route::prefix('')->group(function () {
        Route::get('iframes/telescope', function () {
            return view('dashboard.iframes.iframe', ['iframeUrl' => 'dashboard/telescope']);
        })->name('dashboard.iframes.telescope');

        Route::get('iframes/laravel-log-viewer', function () {
            return view('dashboard.iframes.iframe', ['iframeUrl' => 'dashboard/laravel-log-viewer']);
        });

        Route::get('iframes/heycommunity-log-viewer', function () {
            return view('dashboard.iframes.iframe', ['iframeUrl' => 'dashboard/heycommunity-log-viewer']);
        });
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//
// 登入和登出
Route::middleware(['guest'])->group(function () {
    Route::get('login', 'AuthController@login')->name('web.auth.login');
    Route::post('login', 'AuthController@loginHandler')->name('web.auth.login-handler');
});
Route::post('logout', 'AuthController@logoutHandler')->name('web.auth.logout-handler');

//
// 首页
Route::get('/', function () {
    return redirect()->route('web.posts.index');
})->name('web.home');

//
// User routes
Route::prefix('users')->group(function () {
    Route::get('{user}', 'UserController@show')->name('web.users.show');
});

//
// dev routes
if (app()->environment(['local'])) {
    Route::prefix('debug')->group(function () {
        Route::get('/', 'DebugController@index')->name('web.debug.index');
    });
}

app/Http/Controllers/Api/CarouselController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\CommonResource;
use App\Models\Carousel;
use Illuminate\Http\Request;

class CarouselController extends Controller
{
    public function index(Request $request)
    {
        if (! in_array($request->get('type'), array_keys(Carousel::$types))) {
            return redirect()->route($request->route()->getName(), ['type' => array_key_first(Carousel::$types)]);
        }

        $carousels = Carousel::where('type', $request->get('type'))
            ->where('status', 1)
            ->orderByRaw('ISNULL(sort), sort ASC')
            ->orderByDesc('id')
            ->get();

        return CommonResource::collection($carousels);
    }
}

app/Http/Controllers/Dashboard/Analytics/IncreaseController.php
<?php

namespace App\Http\Controllers\Dashboard\Analytics;

use App\Http\Controllers\Controller;
use App\Models\Common\Comment;
use App\Models\Common\Thumb;
use App\Models\User;
use Illuminate\Http\Request;
use Modules\Post\Entities\Post;

class IncreaseController extends Controller
{
    public function index(Request $request)
    {
        $userIncreaseData = User::whereDate('created_at', '>=', today()->subDays(6))->latest()->get();
        $userActiveData = User::whereDate('last_active_at', '>=', today()->subDays(6))->orderByDesc('last_active_at')->get();
        $postIncreaseData = Post::whereDate('created_at', '>=', today()->subDays(6))->latest()->get();
        $commentIncreaseData = Comment::whereDate('created_at', '>=', today()->subDays(6))->latest()->get();
        $thumbUpIncreaseData = Thumb::where('type', 'thumb_up')->whereDate('created_at', '>=', today()->subDays(6))->latest()->get();

        return view('dashboard.analytics.increases.index', compact(
            'userIncreaseData',
            'userActiveData',
            'postIncreaseData',
            'commentIncreaseData',
            'thumbUpIncreaseData',
        ));
    }
}

app/Http/Controllers/Dashboard/Analytics/UserController.php
<?php

namespace App\Http\Controllers\Dashboard\Analytics;

use App\Http\Controllers\Controller;
use App\Models\Analytics\AnalyticsBase;
use App\Models\User;
use App\Models\VisitorLog;

class UserController extends Controller
{
    public function index()
    {
        $startDate = now()->subDays(31);
        $endDate = now();

        // 用户图表配置
        $userLineChartConfigure = AnalyticsBase::makeLineChartConfigure($startDate, $endDate, [
            ['name' => '用户增长', 'class' => User::class, 'color' => '#2c7be5'],
            ['name' => '用户活跃', 'class' => VisitorLog::class,
                'color' => '#2a9d8f', 'count_column' => 'DISTINCT user_id'],
        ]);

        // 最近 7 天活跃用户，每页 100 用户
        $user7DaysActiveData = (function () {
            $result = [];

            foreach (range(0, 6) as $subDayNum) {
                $date = now()->subDays($subDayNum);
                $result[$date->format('Y-m-d')] = VisitorLog::activeUserOfDate($date)->paginate(100);
            }

            return $result;
        })();

        return view('dashboard.analytics.users.index', compact('userLineChartConfigure', 'user7DaysActiveData'));
    }
}

app/Http/Controllers/Dashboard/AuthController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    /**
     * 登入页面
     */
    public function login()
    {
        return view('dashboard.auth.login');
    }

    /**
     * 登入处理
     */
    public function loginHandler(Request $request)
    {
        $request->validate([
            'phone'         =>  'required|phone',
            'password'      =>  'required|string',
        ]);

        if (Auth::attempt($request->only(['phone', 'password']), true)) {
            return redirect()->route('dashboard.index');
        } else {
            return back()->withInput()->withErrors([
                'phone' =>  '手机号码或密码不正确',
            ]);
        }
    }

    /**
     * 登出处理
     */
    public function logoutHandler()
    {
        Auth::logout();

        return redirect()->route('dashboard.auth.login');
    }
}

app/Http/Controllers/Dashboard/CarouselController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Carousel;
use Illuminate\Http\Request;

class CarouselController extends Controller
{
    /**
     * 列表页
     */
    public function index(Request $request)
    {
        if (! in_array($request->get('type'), array_keys(Carousel::$types))) {
            return redirect()->route($request->route()->getName(), ['type' => array_key_first(Carousel::$types)]);
        }

        $carousels = Carousel::where('type', $request->get('type'))
            ->orderByRaw('ISNULL(sort), sort ASC')
            ->orderByDesc('id')
            ->paginate();

        return view('dashboard.carousels.index', compact('carousels'));
    }

    /**
     * 创建页
     */
    public function create(Carousel $carousel)
    {
        $carousel->setAttribute('type', request('type'));

        return view('dashboard.carousels.create', compact('carousel'));
    }

    /**
     * 创建处理
     */
    public function store(Request $request, Carousel $carousel)
    {
        $request->validate([
            'type'              =>  'required|string',
            'image_path'        =>  'required|image',
            'title'             =>  'required|string',
            'link'              =>  'required|string',
            'content'           =>  'nullable|string',
            'sort'              =>  'nullable|string',
            'status'            =>  'required|integer',
        ]);

        $carousel->setAttribute('type', $request->get('type'));
        $carousel->setAttribute('title', $request->get('title'));
        $carousel->setAttribute('content', $request->get('content'));
        $carousel->setAttribute('link', $request->get('link'));
        $carousel->setAttribute('sort', $request->get('sort'));
        $carousel->setAttribute('status', $request->get('status'));

        if ($request->has('image_path')) {
            $imagePath = $request->file('image_path')->store('uploads/carousels/images');
            $carousel->setAttribute('image_path', $imagePath);
        }

        if ($carousel->save()) {
            flash('创建成功')->success();
            return redirect()->route('dashboard.carousels.index', ['type' => $carousel->getAttribute('type')]);
        } else {
            flash('创建失败')->error();
            return redirect()->back()->withInput();
        }
    }

    /**
     * 编辑页
     */
    public function edit(Carousel $carousel)
    {
        return view('dashboard.carousels.edit', compact('carousel'));
    }

    /**
     * 更新处理
     */
    public function update(Request $request, Carousel $carousel)
    {
        $request->validate([
            'type'              =>  'required|string',
            'image_path'        =>  'nullable|image',
            'title'             =>  'required|string',
            'link'              =>  'required|string',
            'content'           =>  'nullable|string',
            'sort'              =>  'nullable|string',
            'status'            =>  'required|integer',
        ]);


        $carousel->setAttribute('type', $request->get('type'));
        $carousel->setAttribute('title', $request->get('title'));
        $carousel->setAttribute('content', $request->get('content'));
        $carousel->setAttribute('link', $request->get('link'));
        $carousel->setAttribute('sort', $request->get('sort'));
        $carousel->setAttribute('status', $request->get('status'));

        if ($request->has('image_path')) {
            $imagePath = $request->file('image_path')->store('uploads/carousels/images');
            $carousel->setAttribute('image_path', $imagePath);
        }

        if ($carousel->save()) {
            flash('更新成功')->success();
            return redirect()->route('dashboard.carousels.index', ['type' => $carousel->getAttribute('type')]);
        } else {
            flash('更新失败')->error();
            return redirect()->back()->withInput();
        }
    }

    /**
     * 删除处理
     */
    public function destroy(Carousel $carousel)
    {
        $carousel->delete();

        flash('操作成功')->success();
        return redirect()->route('dashboard.carousels.index', ['type' => $carousel->type]);
    }
}

app/Http/Controllers/Dashboard/CommentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Common\Comment;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * 首页面
     */
    public function index()
    {
        $comments = Comment::with([
            'user' => function ($query) {
                $query->select('id', 'avatar', 'nickname');
            },
            'parent' => function ($query) {
                $query->select('id', 'user_id', 'entity_class', 'entity_id');
            },
            'parent.user' => function ($query) {
                $query->select('id', 'avatar', 'nickname');
            },
            'commentable' => function ($query) {
                $query->select('id', 'user_id');
            },
            'commentable.user' => function ($query) {
                $query->select('id', 'avatar', 'nickname');
            },
        ])->latest()->paginate();

        return view('dashboard.comments.index', compact('comments'));
    }

    /**
     * 详情页面
     */
    public function show(Comment $comment)
    {
        $post = $comment->entity;

        return view('dashboard.comments.show', compact('comment', 'post'));
    }
}

app/Http/Controllers/Dashboard/PostController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Modules\Post\Entities\Post;

class PostController extends Controller
{
    /**
     * 列表页
     */
    public function index()
    {
        $posts = Post::with([
            'user' => function ($query) {
                $query->select('id', 'avatar', 'nickname');
            },
            'video' => function ($query) {
                $query->select('id', 'post_id', 'file_path');
            },
            'images' => function ($query) {
                $query->select('id', 'post_id', 'file_path');
            },
        ])->latest()->paginate();

        return view('dashboard.posts.index', compact('posts'));
    }

    /**
     * 详情页
     */
    public function show(Post $post)
    {
        return view('dashboard.posts.show', compact('post'));
    }
}

app/Http/Controllers/Dashboard/ThumbController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Common\Thumb;
use Illuminate\Http\Request;

class ThumbController extends Controller
{
    public function index()
    {
        $thumbs = Thumb::with([
            'user' => function ($query) {
                $query->select('id', 'avatar', 'nickname');
            },
            'thumbable' => function ($query) {
                $query->select('id', 'user_id');
            },
            'thumbable.user' => function ($query) {
                $query->select('id', 'avatar', 'nickname');
            },
        ])->latest()->paginate();

        return view('dashboard.thumbs.index', compact('thumbs'));
    }
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * 列表页
     */
    public function index(Request $request)
    {
        $request->validate([
            'order-by'          =>  'nullable|string',
            'order-direction'   =>  'nullable|string|in:DESC,ASC',
        ]);

        $userQuery = User::query();

        // OrderBy
        $requestOrderBy = $request->get('order-by');
        $requestOrderDirection = $request->get('order-direction');
        switch ($requestOrderBy) {
            case 'last_active_at':
                $userQuery->orderBy('last_active_at', $requestOrderDirection ?: 'DESC');
                break;
            case 'created_at':
                $userQuery->orderBy('created_at', $requestOrderDirection ?: 'DESC');
                break;
            default:
                $userQuery->orderBy('last_active_at', $requestOrderDirection ?: 'DESC');
                view()->share('requestOrderBy', 'last_active_at');
                view()->share('requestOrderDirection', 'DESC');
                break;
        }

        $users = $userQuery->paginate()->appends([
            'order-by'          =>  $request->get('order-by'),
            'order-direction'   =>  $request->get('order-direction')
        ]);

        return view('dashboard.users.index', compact('users'));
    }

    /**
     * 详情页
     */
    public function show(User $user)
    {
        return view('dashboard.users.show', compact('user'));
    }
}

app/Http/Controllers/Dashboard/UserReportController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\UserReport;
use Illuminate\Http\Request;

class UserReportController extends Controller
{
    /**
     * 列表页
     */
    public function index()
    {
        $userReports = UserReport::latest()->paginate();

        return view('dashboard.user-reports.index', compact('userReports'));
    }
}

resources/views/dashboard/carousels/_form.blade.php
<div class="row">
  <div class="col-md-4">
    <div class="form-group">
      <label class="form-label">类别</label>
      <select name="type" class="form-select {{ $errors->has('type') ? 'is-invalid' : null }}">
        @foreach (\App\Models\Carousel::$types as $typeValue => $typeName)
          <option value="{{ $typeValue }}" {{ $typeValue === old('type', $carousel->type) ? 'selected' : null }}>{{ $typeName }}</option>
        @endforeach
      </select>
      <div class="invalid-feedback d-block">{{ $errors->first('type') }}</div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="form-group">
      <label class="form-label">图片</label>
      <input {{ $carousel->image_path ? null : 'required' }} name="image_path" type="file" class="form-control {{ $errors->has('image_path') ? 'is-invalid' : null }}" value="{{ old('image_path') }}" accept="image/*">
      <div class="invalid-feedback">{{ $errors->first('image_path') }}</div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <label class="form-label">标题</label>
      <input name="title" type="text" class="form-control {{ $errors->has('title') ? 'is-invalid' : null }}" value="{{ old('title', $carousel->title) }}">
      <div class="invalid-feedback">{{ $errors->first('title') }}</div>
    </div>
    <div class="form-group">
      <label class="form-label">链接</label>
      <input name="link" type="text" class="form-control {{ $errors->has('link') ? 'is-invalid' : null }}" value="{{ old('link', $carousel->link) }}">
      <div class="invalid-feedback">{{ $errors->first('link') }}</div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <label class="form-label">内容</label>
      <textarea name="content" rows="5" class="form-control {{ $errors->has('content') ? 'is-invalid' : null }}">{{ old('content', $carousel->content) }}</textarea>
      <div class="invalid-feedback">{{ $errors->first('content') }}</div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <label class="form-label">排序</label>
      <input name="sort" type="text" class="form-control {{ $errors->has('sort') ? 'is-invalid' : null }}" value="{{ old('sort', $carousel->sort) }}">
      <div class="invalid-feedback">{{ $errors->first('sort') }}</div>
      <div class="form-text">
        <div>可为空；数值越小越靠前。</div>
        <div></div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <label class="form-label">状态</label>
      <select name="status" class="form-select {{ $errors->has('status') ? 'is-invalid' : null }}">
        @foreach (\App\Models\Carousel::$statuses as $statusValue => $statusName)
          <option value="{{ $statusValue }}" {{ $statusValue === old('status', $carousel->status) ? 'selected' : null }}>{{ $statusName }}</option>
        @endforeach
      </select>
      <div class="invalid-feedback">{{ $errors->first('status') }}</div>
    </div>
  </div>
</div>

resources/views/dashboard/carousels/create.blade.php
@extends('dashboard.layouts.default')

@section('mainContent')
<div class="main-content">
  <div class="header">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-end">
          <div class="col">
            <h6 class="header-pretitle">Carousels</h6>
            <h1 class="header-title">焦点图</h1>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <div id="section-content">
              <form id="form-article" action="{{ route('dashboard.carousels.store') }}" method="POST"
                    enctype="multipart/form-data"
                    onsubmit="formSubmit(event)">
                {{ csrf_field() }}

                @include('dashboard.carousels._form')

                <button type="submit" class="btn w-100 btn-primary">创建</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/dashboard/carousels/edit.blade.php
@extends('dashboard.layouts.default')

@section('mainContent')
<div class="main-content">
  <div class="header">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-end">
          <div class="col">
            <h6 class="header-pretitle">Carousels</h6>
            <h1 class="header-title">焦点图</h1>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <div id="section-content">
              <form id="form-article" action="{{ route('dashboard.carousels.update', $carousel) }}" method="POST"
                    enctype="multipart/form-data"
                    onsubmit="formSubmit(event)">
                {{ method_field('PATCH')}}
                {{ csrf_field() }}

                @include('dashboard.carousels._form')

                <button type="submit" class="btn w-100 btn-primary">更新</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/dashboard/carousels/index.blade.php
@extends('dashboard.layouts.default')

@section('mainContent')
<div class="main-content">
  <div class="header">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-end">
          <div class="col">
            <h6 class="header-pretitle">Carousels</h6>
            <h1 class="header-title">焦点图</h1>
          </div>
          <div class="col-auto">
            <a href="{{ route('dashboard.carousels.create', ['type' => request('type')]) }}" class="btn btn-primary lift"><i class="fe fe-plus"></i> 新增</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="table-responsive mb-0">
            <table class="table table-sm table-nowrap card-table">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>类型</th>
                  <th>图片</th>
                  <th>标题</th>
                  <th>链接</th>
                  <th>排序</th>
                  <th>状态</th>
                  <th>创建时间</th>
                  <th>操作</th>
                </tr>
              </thead>
              <tbody>
                @unless($carousels->count())
                  <tr><td colspan="100">暂无数据</td></tr>
                @endunless

                @foreach ($carousels as $carousel)
                  <tr>
                    <td>{{ $carousel->id }}</td>
                    <td>{{ \App\Models\Carousel::$types[$carousel->type] ?? '未知' }}</td>
                    <td>
                      <a target="_blank" href="{{ asset($carousel->image_path) }}">
                        <img src="{{ asset($carousel->image_path) }}" style="height:40px;">
                      </a>
                    </td>
                    <td>{{ $carousel->title }}</td>
                    <td>{{ $carousel->link }}</td>
                    <td>{{ $carousel->sort }}</td>
                    <td>{{ \App\Models\Carousel::$statuses[$carousel->status] ?? '未知' }}</td>
                    <td>{{ $carousel->created_at }}</td>
                    <td>
                      <a href="{{ route('dashboard.carousels.edit', $carousel) }}" class="btn btn-sm btn-light d-inline-block lift"><i class="fe fe-edit-2"></i></a>

                      <div class="btn-group d-inline-block ms-2">
                        <button type="button" class="btn btn-sm btn-light dropdown-toggle lift" data-bs-toggle="dropdown"></button>
                        <div class="dropdown-menu dropdown-menu-end dropdown-menu-sm">
                          <a class="dropdown-item text-danger" href="{{ route('dashboard.carousels.delete', $carousel) }}">删除</a>
                        </div>
                      </div>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>

        <div class="mb-5">{{ $carousels->links() }}</div>
      </div>
    </div>
  </div>
</div>
@endsection