routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

//
// 登入和登出
Route::middleware(['web'])->group(function () {
    Route::middleware(['guest.dashboard'])->group(function () {
        Route::get('login', 'AuthController@login')->name('dashboard.auth.login');
        Route::post('login', 'AuthController@loginHandler')->name('dashboard.auth.login-handler');
    });

    Route::post('logout', 'AuthController@logoutHandler')->name('dashboard.auth.logout-handler');
});

//
// 管理平台
Route::middleware(['web', 'auth.dashboard'])->group(function () {
    Route::get('/', 'HomeController@index')->name('dashboard.index');

    // 焦点图
    Route::any('carousels/{carousel}/delete', 'CarouselController@destroy')->name('dashboard.carousels.delete')->where('carousel', '[0-9]+');
    Route::name('dashboard')->resource('carousels', 'CarouselController');

    // 用户
    Route::prefix('users')->group(function () {
        Route::get('/', 'UserController@index')->name('dashboard.users.index');
        Route::get('{user}', 'UserController@show')->name('dashboard.users.show')->where('user', '[0-9]+');
    });

    // 评论
    Route::prefix('comments')->group(function () {
        Route::get('/', 'CommentController@index')->name('dashboard.comments.index');
        Route::get('{comment}', 'CommentController@show')->name('dashboard.comments.show')->where('comment', '[0-9]+');
    });

    // 点赞
    Route::prefix('')->group(function () {
        Route::get('thumbs', 'ThumbController@index')->name('dashboard.thumbs.index');
    });

    // 用户报告
    Route::prefix('user-reports')->group(function () {
        Route::get('/', 'UserReportController@index')->name('dashboard.user-reports.index');
    });

    // 数据分析
    Route::prefix('analytics')->group(function () {
        Route::get('/', function () {
            return redirect()->route('dashboard.analytics.users');
        })->name('dashboard.analytics.index');

        Route::get('increases', 'Analytics\IncreaseController@index')->name('dashboard.analytics.increases');

        Route::get('users', 'Analytics\UserController@index')->name('dashboard.analytics.users');
    });

    // 访客日志
    Route::prefix('visitor-logs')->group(function () {
        Route::get('/', 'VisitorLogController@index')->name('dashboard.visitor-logs.index');
        Route::get('date', 'VisitorLogController@date')->name('dashboard.visitor-logs.date');
    });

    // 其他
    Route::prefix('')->group(function () {
        Route::get('iframes/telescope', function () {
            return view('dashboard.iframes.iframe', ['iframeUrl' => 'dashboard/telescope']);
        })->name('dashboard.iframes.telescope');

        Route::get('iframes/laravel-log-viewer', function () {
            return view('dashboard.iframes.iframe', ['iframeUrl' => 'dashboard/laravel-log-viewer']);
        });

        Route::get('iframes/heycommunity-log-viewer', function () {
            return view('dashboard.iframes.iframe', ['iframeUrl' => 'dashboard/heycommunity-log-viewer']);
        });
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//
// 登入和登出
Route::middleware(['guest'])->group(function () {
    Route::get('login', 'AuthController@login')->name('web.auth.login');
    Route::post('login', 'AuthController@loginHandler')->name('web.auth.login-handler');
});
Route::post('logout', 'AuthController@logoutHandler')->name('web.auth.logout-handler');

//
// 首页
Route::get('/', function () {
    return redirect()->route('web.posts.index');
})->name('web.home');

//
// User routes
Route::prefix('users')->group(function () {
    Route::get('{user}', 'UserController@show')->name('web.users.show');
});

//
// dev routes
if (app()->environment(['local'])) {
    Route::prefix('debug')->group(function () {
        Route::get('/', 'DebugController@index')->name('web.debug.index');
    });
}

app/Models/Common/Comment.php
<?php

namespace App\Models\Common;

use App\Models\Model;

class Comment extends Model
{
    use EntityTrial;

    /**
     * Statuses
     */
    public static $statuses = [
        0       =>  '待审核',
        1       =>  '已发布',
    ];

    /**
     * Related EntityModel
     */
    public function commentable()
    {
        return $this->morphTo('commentable', 'entity_class', 'entity_id')->withTrashed();
    }

    /**
     * Related EntityModel
     */
    public function entity()
    {
        // return $this->belongsTo($this->entity_class, 'entity_id')->withTrashed();     // TODO: 测试新的关联写法，一段时间后删除
        return $this->morphTo('commentable', 'entity_class', 'entity_id')->withTrashed();
    }

    /**
     * Related ParentComment
     */
    public function parent()
    {
        return $this->belongsTo(self::class, 'parent_id')->with('user');
    }

    /**
     * Related Thumb
     */
    public function thumbs()
    {
        return $this->morphMany(Thumb::class, 'thumbable', 'entity_class', 'entity_id');
    }

    /**
     * Related Comment
     */
    public function comments()
    {
        return $this->hasMany(self::class, 'parent_id', 'id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use App\Casts\Assert;
use App\Models\Common\Comment;
use App\Models\Common\Thumb;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens;
use Modules\Post\Entities\Post;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    // TODO: post_num, comment_num, thumb_up_num 字段添加到数据表中
    protected $appends = ['post_num', 'comment_num', 'thumb_up_num'];

    public static $genders = [
        0       =>  '未设定',
        1       =>  '男',
        2       =>  '女',
    ];

    /**
     * The guarded column
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at'     =>  'datetime',
        'wx_user_info'          =>  'array',
        'last_active_at'        =>  'datetime',

        'avatar'                =>  Assert::class . ':imageView2/2/w/300',
        'cover'                 =>  Assert::class,
    ];

    /**
     * Related ThumbUp
     */
    public function upThumbs()
    {
        return $this->hasMany(Thumb::class)->where('type', 'thumb_up');
    }

    /**
     * Related ThumbDown
     */
    public function downThumbs()
    {
        return $this->hasMany(Thumb::class)->where('type', 'thumb_down');
    }

    /**
     * Related Post
     */
    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    /**
     * Related Comments
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * Related Comments
     */
    public function postComments()
    {
        return $this->hasMany(Comment::class)->where('entity_class', Post::class);
    }

    /**
     * Get nickname attr
     */
    public function getNicknameAttribute($value)
    {
        return Str::limit($value, 10 * 2, '');
    }

    /**
     * Get post_num attr
     */
    public function getPostNumAttribute()
    {
        return $this->posts()->count();
    }

    /**
     * Get comment_num attr
     */
    public function getCommentNumAttribute()
    {
        return $this->comments()->count();
    }

    /**
     * Get post_num attr
     */
    public function getThumbUpNumAttribute()
    {
        return $this->upThumbs()->count();
    }

    /**
     * Get unread_notice_num attr
     */
    public function getUnreadNoticeNumAttribute()
    {
        return Notice::where(['user_id' => $this->id, 'is_read' => false])->count();
    }

    /**
     * 用户活跃天数
     * TODO: 字段加到表中
     */
    public function getActiveDayNumAttribute()
    {
        return VisitorLog::query()
            ->where('user_id', $this->id)
            ->select([
                DB::raw('DATE(created_at) as date'),
                DB::raw('COUNT(*) as total_num'),
            ])
            ->groupBy('date')
            ->get()->count();
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\UserResource;
use App\Models\User;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class UserController extends Controller
{
    /**
     * User ping
     */
    public function ping(Request $request)
    {
        $user = Auth::guard('sanctum')->user();

        if ($user) {
            return [
                'data'  =>  [
                    'unread_notice_num'     =>  $user->unread_notice_num,
                ],
            ];
        }

        return ['message' => 'OK'];
    }

    /**
     * 微信小程序用户 Signup
     *
     * 打开小程序后请求此 API，用于追踪用户访问
     * 如果未注册，则进行初步注册: status = 0
     */
    public function wxappSignup(Request $request)
    {
        $request->validate([
            'code'      =>  'required|string',
        ]);

        $miniProgram = \EasyWeChat::miniProgram();
        $wxRes = $miniProgram->auth->session($request->code);

        if (isset($wxRes['openid'])) {
            $user = User::firstOrCreate([
                'wx_open_id'        =>  $wxRes['openid'],
            ], [
                'last_active_at'    =>  now(),
            ]);
            $user->token = $user->createToken('token')->plainTextToken;

            Log::channel('hc')->info('[wxappUserSignup-success] 操作成功', ['wxRes' => $wxRes, 'user' => $user->getAttributes(), 'headers' => $request->server]);
            return new UserResource($user);
        } else {
            Log::channel('hc')->warning('[wxappUserSignup-fail] 操作失败', ['wxRes' => $wxRes, 'headers' => $request->server]);
            return response()->json(['message' => $wxRes['errmsg']], 500);
        }
    }

    /**
     * 微信小程序恢复登录
     */
    public function wxappRestoreLogin(Request $request)
    {
        $user = Auth::guard('sanctum')->user();

        if ($user) {
            return new UserResource($user);
        } else {
            return response()->json(['message' => 'Forbidden'], 403);
        }
    }

    /**
     * 微信小程序用户登录
     */
    public function wxappLogin(Request $request)
    {
        $request->validate([
            'code'      =>  'required|string',
            'user_info' =>  'required|array',
        ]);

        $miniProgram = \EasyWeChat::miniProgram();
        $wxRes = $miniProgram->auth->session($request->code);

        if (isset($wxRes['openid'])) {
            $user = User::firstOrCreate(['wx_open_id' => $wxRes['openid']]);

            // 更新用户资料
            if ($user->status === 0) {
                $wxUserInfo = $request->get('user_info');

                // 把用户头像保存在本地
                $client = new Client();
                $avatarData = $client->request('get', $wxUserInfo['avatarUrl'])->getBody()->getContents();
                $avatarPath = 'uploads/users/avatars/' . Str::random(40) . '.jpg';
                Storage::put($avatarPath, $avatarData);

                $user->update([
                    'nickname'  =>  $wxUserInfo['nickName'],
                    'gender'    =>  $wxUserInfo['gender'],
                    'avatar'    =>  $avatarPath,

                    'wx_user_info'  =>  $wxUserInfo,
                    'status'    =>  1,
                ]);
            }

            $user->token = $user->createToken('token')->plainTextToken;

            Log::channel('hc')->info('[wxappUserLogin-success] 用户登录成功', ['wxRes' => $wxRes, 'user' => $user->getAttributes(), 'headers' => $request->server]);
            return new UserResource($user);
        } else {
            Log::channel('hc')->warning('[wxappUserLogin-fail] 用户登录失败', ['wxRes' => $wxRes, 'headers' => $request->server]);
            return response()->json(['message' => $wxRes['errmsg']], 500);
        }

    }

    /**
     * User logout
     */
    public function logout(Request $request)
    {
        $user = $request->user();

        // $user->tokens()->where('name', 'token')->delete();       // 删除全部 token
        $user->currentAccessToken()->delete();                      // 仅删除当前访问的 token

        return response()->noContent();
    }

    /**
     * 用户信息
     */
    public function show(Request $request, User $user)
    {
        return new UserResource($user);
    }

    /**
     * 我的信息
     */
    public function mineShow(Request $request)
    {
        $user = $request->user();

        return new UserResource($user);
    }

    /**
     * 更新我的资料
     */
    public function mineUpdate(Request $request)
    {
        $request->validate([
            'nickname'      =>  'required|string|min:2|max:10',
            'bio'           =>  'nullable|string|max:20',
            'gender'        =>  'nullable|integer|in:0,1,2',
            'phone'         =>  'nullable|phone',
            'email'         =>  'nullable|email',
            'intro'         =>  'nullable|string|max:300',
        ]);

        $user = $request->user();
        $data = $request->only(['nickname', 'bio', 'gender', 'phone', 'email', 'intro']);

        $user->update($data);

        return new UserResource($user);
    }

    /**
     * 更新我的头像
     */
    public function mineAvatarUpdate(Request $request)
    {
        $request->validate([
            'file'      =>  'required|image',
        ]);

        // 小程序 内容安全检测
        $app = app('wechat.mini_program');
        $result = $app->content_security->checkImage($request->file('file'));
        if ($result['errcode'] === 87014) {
            return response([
                'errcode'   =>  $result['errcode'],
                'errmsg'    =>  $result['errmsg'],
                'message'   =>  '图片涉及违规敏感信息',
            ], 403);
        }

        $user = $request->user();
        $filePath = $request->file('file')->store('uploads/users/avatars');
        $user->update(['avatar' => $filePath]);

        return new UserResource($user);
    }

    /**
     * 更新我的封面
     */
    public function mineCoverUpdate(Request $request)
    {
        $request->validate([
            'file'      =>  'required|image',
        ]);

        // 小程序 内容安全检测
        $app = app('wechat.mini_program');
        $result = $app->content_security->checkImage($request->file('file'));
        if ($result['errcode'] === 87014) {
            return response([
                'errcode'   =>  $result['errcode'],
                'errmsg'    =>  $result['errmsg'],
                'message'   =>  '图片涉及违规敏感信息',
            ], 403);
        }

        $user = $request->user();
        $filePath = $request->file('file')->store('uploads/users/cover');
        $user->update(['cover' => $filePath]);

        return new UserResource($user);
    }

    /**
     * 同步微信的用户资料
     */
    public function mineSyncWxProfile(Request $request)
    {
        $this->validate($request, [
            'nickName'      =>  'nullable|string',
            'gender'        =>  'nullable|integer',
            'avatarUrl'     =>  'nullable|string',
            'province'      =>  'nullable|string',
            'city'          =>  'nullable|string',
        ]);

        $user = $request->user();

        $data = ['wx_user_info' => $request->all()];
        if ($request->get('avatarUrl')) {
            $client = new Client();
            $avatarData = $client->request('get', $request->get('avatarUrl'))->getBody()->getContents();
            $avatarPath = 'uploads/users/avatars/' . Str::random(40) . '.jpg';
            Storage::put($avatarPath, $avatarData);
            $data['avatar'] = $avatarPath;
        }
        if ($request->get('nickName')) $data['nickname'] = $request->get('nickName');
        if ($request->get('gender')) $data['gender'] = $request->get('gender');

        if ($data) {
            $user->update($data);
        }

        return new UserResource($user);
    }
}

app/Http/Controllers/Dashboard/Analytics/UserController.php
<?php

namespace App\Http\Controllers\Dashboard\Analytics;

use App\Http\Controllers\Controller;
use App\Models\Analytics\AnalyticsBase;
use App\Models\User;
use App\Models\VisitorLog;

class UserController extends Controller
{
    public function index()
    {
        $startDate = now()->subDays(31);
        $endDate = now();

        // 用户图表配置
        $userLineChartConfigure = AnalyticsBase::makeLineChartConfigure($startDate, $endDate, [
            ['name' => '用户增长', 'class' => User::class, 'color' => '#2c7be5'],
            ['name' => '用户活跃', 'class' => VisitorLog::class,
                'color' => '#2a9d8f', 'count_column' => 'DISTINCT user_id'],
        ]);

        // 最近 7 天活跃用户，每页 100 用户
        $user7DaysActiveData = (function () {
            $result = [];

            foreach (range(0, 6) as $subDayNum) {
                $date = now()->subDays($subDayNum);
                $result[$date->format('Y-m-d')] = VisitorLog::activeUserOfDate($date)->paginate(100);
            }

            return $result;
        })();

        return view('dashboard.analytics.users.index', compact('userLineChartConfigure', 'user7DaysActiveData'));
    }
}

app/Http/Controllers/Web/UserController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Models\User;

class UserController extends Controller
{
    /**
     * 详情页
     */
    public function show(User $user)
    {
        return view('web.users.show', compact('user'));
    }
}

resources/views/common/users/_item-comment-card.blade.php
<div class="card">
  <div class="card-body">{{ $comment->content }}</div>
  <div class="card-footer py-2 bg-light-soft">
    <div class="row">
      <div class="col">
        <span class="text-muted small">{{ $comment->entity_name }}({{ $comment->entity_id }})</span>
      </div>
      <div class="col-auto">
        <span class="text-muted small">{{ $comment->created_at }}</span>
      </div>
    </div>
  </div>
</div>

resources/views/common/users/_items-comment-card.blade.php
@if ($comments->isEmpty())
  <div class="card"><div class="card-body">暂无评论</div></div>
@else
  @foreach ($comments as $comment)
    @include('common.users._item-comment-card', ['comment' => $comment])
  @endforeach
@endif

resources/views/common/users/_items-up-thumb-card.blade.php
@if ($thumbs->isEmpty())
  <div class="card"><div class="card-body">暂无点赞</div></div>
@else
  @foreach ($thumbs as $thumb)
    <div class="card">
      <div class="card-header">
        <div class="card-header-title">点赞{{ $thumb->entity_name }}({{ $thumb->entity_id }})</div>
        <div><span class="text-muted">{{ $thumb->created_at }}</span></div>
      </div>
      <div class="card-body bg-light-soft">
        @switch($thumb->entity_class)
          @case(\App\Models\Common\Comment::class)
            @include('common.users._item-comment-card', ['comment' => $thumb->entity])
            @break
          @case(\Modules\Post\Entities\Post::class)
            @include('post::common._post-profile', ['post' => $thumb->entity])
            @break
          @case(\Modules\Article\Entities\Article::class)
            @include('article::common._article-profile', ['article' => $thumb->entity])
            @break
          @case(\Modules\Activity\Entities\Activity::class)
            @include('activity::common._activity-profile', ['activity' => $thumb->entity])
            @break
          @default
            <div class="card">
              <div class="card-body">coming soon ..</div>
            </div>
        @endswitch
      </div>
    </div>
  @endforeach
@endif

resources/views/common/users/_user-info-card.blade.php
<div class="card">
  <div class="card-header">
    <h4 class="card-header-title"><i class="fe fe-user me-1"></i> 用户信息</h4>
    <span class="small text-muted">#{{ $user->id }}</span>
  </div>
  <div class="card-body">
    <div class="list-group list-group-flush my-n3">
      <div class="list-group-item py-3">
        <div class="row align-items-center">
          <div class="col"><h5 class="mb-0">简介</h5></div>
          <div class="col-auto"><small class="text-muted">{{ $user->intro }}</small></div>
        </div>
      </div>

      <div class="list-group-item py-3">
        <div class="row align-items-center">
          <div class="col"><h5 class="mb-0">性别</h5></div>
          <div class="col-auto"><small class="text-muted">{{ \App\Models\User::$genders[$user->gender] ?? '未知' }}</small></div>
        </div>
      </div>

      <div class="list-group-item py-3">
        <div class="row align-items-center">
          <div class="col"><h5 class="mb-0">活跃天数</h5></div>
          <div class="col-auto"><small class="text-muted">{{ $user->active_day_num }}</small></div>
        </div>
      </div>

      <div class="list-group-item py-3">
        <div class="row align-items-center">
          <div class="col"><h5 class="mb-0">动态/评论/点赞</h5></div>
          <div class="col-auto"><small class="text-muted">{{ $user->post_num }} / {{ $user->comment_num }} / {{ $user->thumb_up_num }}</small></div>
        </div>
      </div>

      <div class="list-group-item py-3">
        <div class="row align-items-center">
          <div class="col"><h5 class="mb-0">最近活跃时间</h5></div>
          <div class="col-auto">
            <time class="small text-muted" datetime="{{ $user->last_active_at }}"
                  data-bs-toggle="tooltip" title="{{ optional($user->last_active_at)->diffForHumans() }}">{{ $user->last_active_at ?? 'NULL' }}</time>
          </div>
        </div>
      </div>

      <div class="list-group-item py-3">
        <div class="row align-items-center">
          <div class="col"><h5 class="mb-0">注册时间</h5></div>
          <div class="col-auto">
            <time class="small text-muted" datetime="{{ $user->created_at }}"
                  data-bs-toggle="tooltip" title="{{ $user->created_at->diffForHumans() }}">{{ $user->created_at }}</time>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>