Modules/Post/Routes/dashboard.php
<?php

Route::prefix('dashboard/posts')->group(function () {
    Route::get('/', 'PostController@index')->name('dashboard.posts.index');
    Route::get('{post}', 'PostController@show')->name('dashboard.posts.show');

    Route::any('{post}/set-visible', 'PostController@setVisible')->name('dashboard.posts.set-visible');
    Route::any('{post}/set-hidden', 'PostController@setHidden')->name('dashboard.posts.set-hidden');
    Route::any('{post}/destroy', 'PostController@destroy')->name('dashboard.posts.destroy');
});

Modules/Post/Routes/web.php
<?php

Route::prefix('posts')->group(function () {
    Route::get('/', 'PostController@index')->name('web.posts.index');
    Route::get('{post}', 'PostController@show')->name('web.posts.show')->where('post', '[0-9]+');
});

Modules/Post/Entities/Post.php
<?php

namespace Modules\Post\Entities;

use App\Models\Common\Comment;
use App\Models\Common\Thumb;
use App\Models\Model;

class Post extends Model
{
    /**
     * Appends
     */
    protected $appends = ['image_num'];

    /**
     * Statuses
     */
    public static $statuses = [
        0       =>  '待审核',
        1       =>  '已发布',
        2       =>  '已下架',
    ];

    /**
     * newFactory
     */
    protected static function newFactory()
    {
        return \Modules\Post\Database\factories\PostFactory::new();
    }

    /**
     * Related PostImage
     */
    public function images()
    {
        return $this->hasMany(PostImage::class);
    }

    /**
     * Related VideoImage
     */
    public function video()
    {
        return $this->hasOne(PostVideo::class);
    }

    /**
     * 状态名称 Attr
     */
    public function getStatusNameAttribute()
    {
        return self::$statuses[$this->getAttribute('status')] ?? '未知';
    }

    /**
     * 图片数量 attr
     */
    public function getImageNumAttribute()
    {
        return $this->images()->count();
    }
}

Modules/Post/Resources/views/common/_post-info-card.blade.php
<div class="card">
  <div class="card-header">
    <h4 class="card-header-title">动态信息</h4>
    <span class="small text-muted">#{{ $post->id }}</span>
  </div>
  <div class="card-body">
    <div class="list-group list-group-flush my-n3">
      <div class="list-group-item py-3">
        <div class="row align-items-center">
          <div class="col"><h5 class="mb-0">发布人</h5></div>
          <div class="col-auto"><a class="small" href="{{ hcRoute('users.show', $post->user) }}">{{ $post->user->nickname }}</a></div>
        </div>
      </div>

      <div class="list-group-item py-3">
        <div class="row align-items-center">
          <div class="col"><h5 class="mb-0">阅读 / 点赞 / 评论</h5></div>
          <div class="col-auto"><small class="text-muted">{{ $post->read_num }} / {{ $post->thumb_up_num }} / {{ $post->comment_num }}</small></div>
        </div>
      </div>

      <div class="list-group-item py-3">
        <div class="row align-items-center">
          <div class="col"><h5 class="mb-0">发布时间</h5></div>
          <div class="col-auto">
            <time class="small text-muted" datetime="{{ $post->created_at }}"
                  data-bs-toggle="tooltip" title="{{ $post->created_at->diffForHumans() }}">{{ $post->created_at }}</time>
          </div>
        </div>
      </div>

      <div class="list-group-item py-3">
        <div class="row align-items-center">
          <div class="col"><h5 class="mb-0">更新时间</h5></div>
          <div class="col-auto">
            <time class="small text-muted" datetime="{{ $post->updated_at }}"
                  data-bs-toggle="tooltip" title="{{ $post->updated_at->diffForHumans() }}">{{ $post->updated_at }}</time>
          </div>
        </div>
      </div>

      <div class="list-group-item py-3">
        <div class="row align-items-center">
          <div class="col"><h5 class="mb-0">状态</h5></div>
          <div class="col-auto"><span class="text-muted small">{{ $post->status_name }}</span></div>
        </div>
      </div>
    </div>
  </div>
</div>

Modules/Post/Resources/views/common/_post-list.blade.php
@if ($posts->isEmpty())
  <div class="card"><div class="card-body">暂无动态</div></div>
@else
  @foreach ($posts as $post)
    @include('post::common._post-profile')
  @endforeach
@endif

Modules/Post/Resources/views/common/_post-profile.blade.php
@php
  if (! isset($showComments)) $showComments = true;
@endphp

<div class="card">
  <div class="card-body">
    <!-- Header -->
    <div class="">
      <div class="row align-items-center">
        <div class="col-auto">
          <a href="{{ hcRoute('users.show', $post->user) }}" class="avatar">
            <img src="{{ $post->user->avatar }}" alt="{{ $post->user->nickname }}" class="avatar-img rounded-circle">
          </a>
        </div>

        <div class="col ms-n2">
          <h4 class="mb-1"><a href="{{ hcRoute('users.show', $post->user) }}">{{ $post->user->nickname }}</a></h4>
          <p class="card-text small text-muted">
            <span class="fe fe-clock"></span>
            <time datetime="{{ $post->created_at }}" data-bs-toggle="tooltip" title="{{ $post->created_at->diffForHumans() }}">{{ $post->created_at }}</time>
          </p>
        </div>

        <div class="col-auto">
          <div class="dropdown">
            <a href="#" class="dropdown-ellipses dropdown-toggle" data-bs-toggle="dropdown">
              <i class="fe fe-more-vertical"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-end">
              <a href="{{ hcRoute('posts.show', $post) }}" class="dropdown-item text-muted">详情</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Content -->
    <div class="mt-3">{!! $post->content !!}</div>

    <!-- Images -->
    <div class="row mt-1 g-2">
      @foreach ($post->images as $image)
        <div class="col col-sm-6 col-md-4 col-auto">
          <img src="{{ $image->file_path }}" class="img-fluid rounded">
        </div>
      @endforeach
    </div>

    <!-- Footer -->
    <div class="mt-3">
      <div class="row">
        <div class="col">
          <a class="btn btn-sm btn-white">
            <i class="fe fe-thumbs-up"></i> {{ $post->thumb_up_num ?: null }}
          </a>
          <a class="btn btn-sm btn-white">
            <i class="fe fe-message-square"></i> {{ $post->comment_num ?: null }}
          </a>
        </div>
      </div>
    </div>

    <!-- Comments -->
    @if ($showComments)
      <hr>
      <div>
        @foreach ($post->comments as $comment)
          <div class="comment mb-0 mt-3">
            <div class="row">
              <div class="col-auto">
                <a class="avatar" href="{{ hcRoute('users.show', $comment->user) }}">
                  <img src="{{ $comment->user->avatar }}" class="avatar-img rounded-circle">
                </a>
              </div>
              <div class="col ms-n2">
                <div class="comment-body">
                  <div class="row">
                    <div class="col">
                      <h5 class="comment-title"><a href="{{ hcRoute('users.show', $comment->user) }}">{{ $comment->user->nickname }}</a></h5>
                    </div>
                    <div class="col-auto">
                      <time class="comment-time" data-bs-toggle="tooltip" title="{{ $comment->created_at->diffForHumans() }}">{{ $comment->created_at }}</time>
                    </div>
                  </div>
                  <p class="comment-text">{{ $comment->content }}</p>
                </div>
              </div>
            </div>
          </div>
        @endforeach
        @unless ($post->comments->count())
          <div class="small text-muted">无评论</div>
        @endunless
      </div>
    @endif
  </div>
</div>